### ISSUE TITLE
Incorrect label below large home widget

### ISSUE THREAD

**Issue by tungmeister** [vonH/skin.xperience1080#59]
At the homescreen the label is incorrect below the large widget. I've set it to display "In theatres now" but the label shows "Trending Movies"

**Comment by xhaggi** [comment]
Which skin version do you use?
Which section (Movies, Home etc.)?

**Comment by tungmeister** [comment]
The latest build and the home section (what I meant by home screen)

**Comment by xhaggi** [comment]
I can't reproduce it. I've switch through all widget types and everything was labeled correctly.

**Comment by tungmeister** [comment]
I've just tested it again ensuring I'm using the latest build from github, the label will for all options apart from the in theatres now and popular movies which are both soured from the MovieDB. There's nothing shown in the debug log when those sources are selected either.

**Comment by xhaggi** [comment]
@tungmeister  could you please file the issue again in our new repo https://github.com/xperience1080/skin.xperience1080/issues

**Comment by xhaggi** [comment]
@tungmeister the issue is fixed in current master and in the next official beta2 release.

**Comment by tungmeister** [comment]
@xhaggi The issue is still present in the latest github build from the other repo

**Comment by xhaggi** [comment]
please report your issue on our new github repo, thanks.
